### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by prasad-1729** [vinayakkailas/image_similarity#1]
WARNING:tensorflow:From C:\Users\prasad\Downloads\root\server\image_vectorizer.py:36: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.gfile.GFile.
Traceback (most recent call last):
  File "C:\Users\prasad\Downloads\root\server\image_vectorizer.py", line 110, in <module>
    image_data = gfile.FastGFile(filename, 'rb').read()
  File "C:\python36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 125, in read
    self._preread_check()
  File "C:\python36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "C:\python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: NewRandomAccessFile failed to Create/Open: uploads/dogs_and_cats/Shoes/Crib Shoes : Access is denied.

; Input/output error

**Comment by prasad-1729** [comment]
only Folder access is denied but  store all images in one folder

**Comment by sudoStatus200** [comment]
@prasad-1729  could you solve it?

**Comment by sudoStatus200** [comment]
code is trying to open folder by assuming its a file that's why error is generating.

**Comment by kodalianiruddho** [comment]
Can you tell me how to solve this error?
