### ISSUE TITLE
Rest-server file name 'allowed_file' is not defined

### ISSUE THREAD

**Issue by Vatsal-Rakholiya** [vinayakkailas/image_similarity#7]
2021-05-20 13:50:13.429732: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-05-20 13:50:13.429868: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
loaded extracted_features
 * Debugger is active!
 * Debugger PIN: 813-924-762
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [20/May/2021 13:50:38] "←[37mGET / HTTP/1.1←[0m" 200 -
127.0.0.1 - - [20/May/2021 13:50:38] "←[33mGET /images/logo.svg HTTP/1.1←[0m" 404 -
image upload
POST
RLaver_shoe.jpg
127.0.0.1 - - [20/May/2021 13:50:43] "←[35m←[1mPOST /imgUpload HTTP/1.1←[0m" 500 -
Traceback (most recent call last):
  File "E:\Vatsal\Personal\Anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "E:\Vatsal\Personal\Anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "E:\Vatsal\Personal\Anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "E:\Vatsal\Personal\Anaconda3\envs\myenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "E:\Vatsal\Personal\Anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Vatsal\Personal\Anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Vatsal\Personal\Anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\Vatsal\Personal\Anaconda3\envs\myenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "E:\Vatsal\Personal\Anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Vatsal\Personal\Anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Vatsal\Personal\Machine Learning\Cilans VN\DL\Deeplearning_Image_Similarity-master\server\rest-server.py", line 72, in upload_img
    if file(file.filename):
TypeError: 'FileStorage' object is not callable
 * Detected change in 'E:\\Vatsal\\Personal\\Machine Learning\\Cilans VN\\DL\\Deeplearning_Image_Similarity-master\\server\\rest-server.py', reloading
 * Restarting with stat
2021-05-20 13:55:37.185053: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-05-20 13:55:37.185222: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
loaded extracted_features
 * Debugger is active!
 * Debugger PIN: 813-924-762
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [20/May/2021 13:56:01] "←[37mGET / HTTP/1.1←[0m" 200 -
127.0.0.1 - - [20/May/2021 13:56:01] "←[33mGET /images/logo.svg HTTP/1.1←[0m" 404 -
image upload
POST
RLaver_shoe.jpg
127.0.0.1 - - [20/May/2021 13:56:05] "←[35m←[1mPOST /imgUpload HTTP/1.1←[0m" 500 -
Traceback (most recent call last):
  File "E:\Vatsal\Personal\Anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "E:\Vatsal\Personal\Anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "E:\Vatsal\Personal\Anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "E:\Vatsal\Personal\Anaconda3\envs\myenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "E:\Vatsal\Personal\Anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Vatsal\Personal\Anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Vatsal\Personal\Anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\Vatsal\Personal\Anaconda3\envs\myenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "E:\Vatsal\Personal\Anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Vatsal\Personal\Anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Vatsal\Personal\Machine Learning\Cilans VN\DL\Deeplearning_Image_Similarity-master\server\rest-server.py", line 72, in upload_img
    if file and allowed_file(file.filename):
NameError: name 'allowed_file' is not defined
![Capture](https://user-images.githubusercontent.com/54349523/118946946-7e39e380-b974-11eb-906b-d921b7d84da0.JPG)

**Comment by Vatsal-Rakholiya** [comment]
Please Reply me at vatsalr2206@gmail.com
Please do fast
